import { Image } from "react-native";
import { images } from "../assets/images";
import { styles } from "../screens/bottom/sendBackAccountScreen/styles";

export const Strings = {
  mobileBanking: 'Mobile banking the world loves.',
  getSendingText:
    'Get sending, spending and saving with your\ncontactless card.',
  getStartedWithAccount: 'Get started with your\naccount!',
  enterEmail: 'Email Address',
  password: 'Password',
  termsTextStart: "I have read and I understand Swift Pay Bank's ",
  termsConditions: 'Terms and conditions ',
  and: 'and ',
  PrivacyPolicy: 'Privacy Policy.',
  yourMobileNum: "What's your mobile number?",
  useAsAccNum: 'We’ll use this as your Swift Pay account number.',
  country: 'Country',
  agreementMsg:
    'By providing your phone number, you agree that we may contact you by SMS/text messaging. Carrier messaging and data rates may apply.',
  verifyPhn: 'Verify your phone number',
  otpHeading: 'Enter the 6-digit code we texted to you at ',
  editNumber: 'Edit Number',
  codeReceive: "Didn't receive the code?",
  resendCode: 'Resend code',
  openingText: 'Your Swift Pay account is\nopen, Victor!',
  announcementNews:
    'Great news, you’ve joined Swift Pay. You can\nnow make transfers and more.',
  accountInfo: 'Account Information',
  accountNum: 'Account Number',
  accountName: 'Account Name',
  institutionName: 'Institution Name',
  accountBalance: 'Account Balance',
  transactionHistory: 'Transaction History',
  accountSettings: 'Account Settings',
  logout: 'Logout',
  continueToApp: 'Continue to the app',
  login: 'Login',
  getStarted: 'Get Started',
  submit: 'Submit',
  verify: 'Verify',
  greetingText: 'Hi, Victor Jim',
  subGreeting: 'Welcome, lets start making payments',
  totalText: 'Total Balance',
  updateText: 'Last updated 2 minutes ago.',
  bankName: 'Swift Pay Bank',
  addMoney: 'Add money',
  myCards: 'My cards',
  sendMoney: 'Send money',
  getStarted: 'Get started',
  quickAccess: 'Quick access',
  airTime: 'Airtime',
  betting: 'Betting',
  dataBundle: 'Data Bundle',
  getMore: 'Get more from your account',
  today: 'TODAY',
  noTransactions: 'You haven’t made any transactions yet.',
  notifications: 'Notifications',
  noNotification: 'You have no notifications',
  notificationArrival: 'Your notifications will appear here when they\narrive.',
  addMoneyCaps: 'Add Money',
  swiftAccNum: 'Swift Pay Account Number',
  sendMoneyCaps: 'Send Money',
  swiftPayUser: 'Swift Pay User',
  sendToUser: 'Send to a Swift Pay User or invite phone contact',
  bankAccount: 'Bank Account',
  sendToBankAcc: 'Send to a bank account',
  eNaira: 'eNaira',
  sendToENaira: 'Send to eNaira account',
  bankTransfer: 'Bank Transfer',
  addMoneyVIA: 'Add money via mobile or internet banking',
  copyNumber: 'Copy number',
  shareInfo: 'Share Info',
  topUp: 'Top-up using Card',
  addDirectlyFromCard: 'Add money directly from your bank card',
  userName: 'Victor Jimoh',
  userAccNum: '8085472417',
  account: 'Account',
  support: 'Support',
  referAndEarn: 'Refer & earn',
  points: 'Earn 2,000 naira for inviting friends to\nSwift Pay Bank',
  logoutText: 'Logout from your account',
  support: 'Support',
  featureRequest: 'Feature requests',
  status: 'Status',
  personalDetails: 'Personal details',
  transactionHistory: 'Transaction history',
  privacy: 'Privacy & security',
  beneficiary: 'Beneficiary\'s name',
  enterYourPasscode: 'Enter your passcode',
  fourDigitPasscode: 'Enter your 4 digit passcode in order to perform this transaction',
  share: 'Share Receipt',
  download: 'Download Receipt',
  transferSuccess: 'Transfer Successful!',
  addMoney: 'Add Money',
  createCard: 'Create a debit card',
  earnInvite: 'Earn ₦ 2,000 for inviting friends to Swi...',
  totalBalance: 'Total Balance',
  totalAmount: '₦ 2,000,000.00',
  change: 'Change',
  continue: 'Continue',
  loading: 'Loading',
  loginToYourAccount: 'Log in to your Swift Pay account.',
  rememberMe: 'Remember Me',
  forgotPassword: 'Forgot Password?',
  passwordForgot: 'Forgot Password',
  forgotSubHeading: 'Oh sorry! Enter your email address below and we will send you a reset link.',
  secureYourAccess: 'Secure your access',
  chooseHowYouWantToUnlockAndEnter: 'Choose how you want to unlock and enter your Swift Pay Bank app.',
  createYourPassword: 'Create your passcode',
  thisWillBeUsedForLoggingInAndAccessYourApp: 'This will be used for logging in and access your app, so please don\'t share it with anyone.',
  justALittleBitMoreAbout: 'Just a little bit more about yourself',
  weNeedSomeAdditionalInformation: 'We need some additional information from you to secure your account.',
  firstName: 'First name',
  lastName: 'Last name',
  dateOfBirthFormat: 'Date of birth (YYYY-MM-DD)',
  verifyYourDetails: 'Verify your details',
  toVerifyYourIdentityWeNeedYouTo: 'To verify your identity, we need you to provide your BVN.',
  thankYouText: 'Thanks for submitting..',
  timeText: 'This will be done in a few seconds.',
  restartText: 'Leaving the app will restart the process.',
  bvnConfirmation: 'BVN Confirmation',
  rememberPassword: 'Remember your password?',
  clickHere: ' Click here',
  faceIdAndTouch: 'Face ID & Touch ID',
  passcodeOnly: 'Passcode only',
  underProgressMsg: 'The content of this screen will be avaialable after some days.',
  transactionReceipt: 'Transaction receipt',
  generatedFromSwiftPayBankOn: 'Generated from Swift Pay Bank on',
  transferStatus: 'Transaction Status',
  transferSuccessful: 'Transfer Successful'
};

export const ScreenNames = {
  AuthStack: 'AuthStack',
  BottomStack: 'BottomStack',
  BoardingScreen: 'OnBoardScreen',
  RegisterationScreen: 'SignUpScreen',
  PhoneScreen: 'PhoneInputScreen',
  OTPScreen: 'OtpScreen',
  UnlockScreen: 'UnlockMethodScreen',
  CreatePascodeScreen: 'CreatePasscodesScreen',
  UserDataScreen: 'UserDetailsScreen',
  BvnScreen: 'BVNVerifyScreen',
  WelcomingScreen: 'WelcomeScreen',
  thankYouScreen: 'ThankYouScreen',
  HomeScreen: 'HomeScreen',
  CardScreen: 'CardScreen',
  SendScreen: 'SendScreen',
  InvestScreen: 'InvestScreen',
  MoreScreen: 'MoreScreen',
  DownloadScreen: 'ReceiptDownloadScreen',
  Home: 'Home',
  Send: 'Send',
  Invest: 'Invest',
  More: 'More',
  Cards: 'Cards',
  sendMoneyBankAccountScreen: 'SendMoneyBankAccountScreen',
  passcodeScreen: "PasscodeScreen",
  successScreen: 'SuccessScreen',
  sendMoneyENairaScreen: 'SendMoneyENairaScreen',
  loginScreen: 'LoginScreen',
  forgotPasswordScreen: 'ForgotPasswordScreen',
  topUpUsingCardScreenStep1: 'TopUpUsingCardScreenStep1',
  topUpUsingCardScreenStep2: 'TopUpUsingCardScreenStep2',
  topUpUsingCardScreenStep3: 'TopUpUsingCardScreenStep3',
  topUpUsingCardScreenStep4: 'TopUpUsingCardScreenStep4',
  topUpUsingCardScreenStep5: 'TopUpUsingCardScreenStep5',
  topUpUsingCardScreenStep6: 'TopUpUsingCardScreenStep6',
  underConstructionScreen: 'UnderConstructionScreen',

};

export const Banks = [
  { label: "National Bank of Pakistan", value: "NBP", icon: () => <Image source={images.nationalBank} style={styles.bankLogo} />, img: images.nationalBank },
  { label: "Habib Bank Limited", value: "HBL", icon: () => <Image source={images.hblBank} style={styles.bankLogo} />, img: images.hblBank },
  { label: "United Bank Limited", value: "UBL", icon: () => <Image source={images.ublBank} style={styles.bankLogo} />, img: images.ublBank },
  { label: "Allied Bank Limited", value: "ABL", icon: () => <Image source={images.alliedBank} style={styles.bankLogo} />, img: images.alliedBank },
  { label: "Meezan Bank", value: "MBL", icon: () => <Image source={images.meezanBank} style={styles.bankLogo} />, img: images.meezanBank },
  { label: "Bank Alfalah", value: "BAFL", icon: () => <Image source={images.alFalahBank} style={styles.bankLogo} />, img: images.alFalahBank },
  { label: "Askari Bank", value: "AKBL", icon: () => <Image source={images.askariBank} style={styles.bankLogo} />, img: images.askariBank },
  // Add more banks as needed
];